edition = "2024"
style_edition = "2024"
max_width = 120
array_width = 60
newline_style = "Unix"
overflow_delimited_expr = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
float_literal_trailing_zero = "IfNoPostfix"
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
#use_field_init_shorthand = true # Undecided on this
reorder_impl_items = true
match_block_trailing_comma = true
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
imports_granularity = "Crate"
imports_layout = "Vertical"
