[package]
name = "df"
description = "A Lua-powered dotfile manager"
version = "0.1.1"
edition = "2024"
rust-version = "1.85.0"
repository = "https://github.com/tehbilly/df"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2.0"
color-eyre = "0.6"

rust-embed = { version = "8.11", features = [] }
dir_spec = "0.5"
clap = { version = "4", features = ["color", "derive"] }
crossterm = { version = "0.29", features = ["event-stream"] }
ratatui = { version = "0.30", features = ["crossterm"] }
mlua = { version = "0.12.0-rc.1", features = ["vendored", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["now", "clock", "serde"] }
walkdir = "2.5"
sha2 = "0.11"
hex = "0.4"
similar = { version = "3.1", features = ["text"] }
# Used for hostname, but I'd like to add helpers for things like distro, desktop env, etc.
whoami = "2.1"
indexmap = "2.14"
comfy-table = "7.2"
# Templating
minijinja = { version = "2.19", features = [] }

[dev-dependencies]
tempfile = "3.27"
assert_cmd = "2.2"

[features]
default = [ "lua55" ]
# Right now we use hardcoded .lua filenames, should probably check for either if we add luau support
# luau = [ "mlua/luau" ]
luajit = [ "mlua/luajit" ]
lua52 = [ "mlua/lua54" ]
lua53 = [ "mlua/lua54" ]
lua54 = [ "mlua/lua54" ]
lua55 = [ "mlua/lua55" ]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"

# Be explicit about metadata for binstall
[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

# Windows gets a zip
[package.metadata.binstall.overrides.'cfg(target_os = "windows")']
pkg-fmt = "zip"
